version: '3.7'

services:
  edd: &edd
    build: &build
      context: .
      args:
        version: "5.7"
        edd_version: "2.10.1"
    ports:
      - 8085:80
    depends_on:
      - mysql
    volumes:
      - /var/www/html
      - ./edd-begateway-gateway:/var/www/html/wp-content/plugins/edd-begateway-gateway
    networks:
      - default
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: edd
      WORDPRESS_DB_HOST: mysql

  mysql:
    image: mysql:5.6
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edd
